sudo: false
language: node_js
node_js:
  - '5.1'
addons: 
  firefox: "43.0"
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - npm install -g codacy-coverage
  - npm install
script: npm run build:travis
after_script:
  - ./deploy.sh
  - cat coverage/**/lcov.info | codacy-coverage
deploy:
  provider: bintray
  file: "bintray.json"
  user: "rkorytkowski"
  key: $BINTRAY_API_KEY
  dry-run: false
  on:
    tags: true
