sudo: false
language: node_js
node_js:
  - '4.2'
install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp bower codacy-coverage
  - npm install
  - bower install
after_script:
    - cat coverage/**/lcov.info | codacy-coverage
deploy:
  provider: bintray
  file: "bintray.json"
  user: "rkorytkowski"
  key: "Bintray API key"
  dry-run: true
  on:
    tags: true
