sudo: false
language: node_js
node_js:
  - '4.2'
install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp bower
  - npm install
  - bower install
